# Generated by Django 4.1.4 on 2022-12-11 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='Placa',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
